import { BlogPost } from "../types"

export const article: BlogPost = {
  slug: "kw-62-how-to-set-up-custom-domain-for-short-links",
  title: "How to Set Up a Custom Domain for Short Links: Complete DNS Guide",
  metaDescription: "Step-by-step guide on how to set up a custom domain for short links. DNS configuration, CNAME records, SSL certificates, and RELURL setup covered in detail.",
  keywords: ["set up custom domain for short links", "custom domain short link", "dns configuration short links", "cname record shortener", "branded short domain setup"],
  landingPage: "/custom-url-shortener",
  category: "Guides",
  date: "June 29, 2026",
  readTime: "9 min read",
  image: "https://picsum.photos/seed/kw-62-how-to-set-up-custom-domain-for-short-links/1200/630",
  imageAlt: "How to Set Up a Custom Domain for Short Links: Complete DNS Guide",
  content: [
    { type: "paragraph", content: "A custom domain transforms your short links from generic utilities into branded assets. Instead of relurl.com/your-link, you get yourbrand.link/your-link. Every click builds brand recognition. Every share displays your domain. Setting this up requires a few DNS changes, but the process is straightforward when you understand each step. This guide covers exactly how to set up a custom domain for short links with RELURL." },
    { type: "heading", content: "Why Use a Custom Domain for Short Links?", level: 2 },
    { type: "paragraph", content: "Trust is the primary reason. A short link on a generic domain tells the user nothing about the destination. A short link on your own domain signals that the link is legitimate and controlled by you. This trust translates directly into higher click-through rates." },
    { type: "paragraph", content: "Brand consistency is the second reason. Every piece of content you share with your branded short domain reinforces your brand identity. Over hundreds of thousands of shares, that repetition builds recognition. A custom domain is essentially free advertising on every link you share." },
    { type: "paragraph", content: "Control is the third reason. If you use a generic shortener domain and the provider shuts down, all your links break. When you own the domain, you can switch the DNS to a different provider and keep all your links working. You never lose the association between your short links and your brand." },
    { type: "heading", content: "What You Need Before Starting", level: 2 },
    { type: "list", items: ["A domain name you own (e.g., yourbrand.link, go.yourbrand.com, or s.co)", "Access to your domain's DNS settings (usually through your domain registrar or hosting provider)", "A RELURL account with custom domain support (available on the relevant plan)", "DNS changes typically take 5-30 minutes to propagate, though some providers take up to 48 hours"] },
    { type: "heading", content: "Step 1: Choose Your Short Domain", level: 2 },
    { type: "paragraph", content: "The best short domains are short, brand-aligned, and easy to type. Common patterns include a subdomain like link.yourbrand.com, a separate domain like yourbrand.link, or a short branded domain like brnd.co. The .link TLD is popular for short links because it describes exactly what the domain does." },
    { type: "paragraph", content: "Avoid domains that are similar to existing popular services, hard to spell over the phone, or too long to qualify as short. The ideal length is under 10 characters for the domain name itself, not counting the TLD." },
    { type: "heading", content: "Step 2: Configure the CNAME Record", level: 2 },
    { type: "paragraph", content: "The CNAME record is the core DNS configuration that connects your domain to RELURL's redirect infrastructure. A CNAME record maps your domain to RELURL's server hostname so incoming requests are routed correctly." },
    { type: "paragraph", content: "Log into your DNS provider's control panel. Navigate to the DNS settings or DNS management section. Create a new CNAME record. For a subdomain like link.yourbrand.com, the host or name field is \"link\" and the target or value field is the CNAME target provided by RELURL. For an apex domain (yourbrand.link without a subdomain), you may need to use an ALIAS or A record depending on your DNS provider, as CNAME records cannot be placed at the root of a domain." },
    { type: "paragraph", content: "The exact CNAME target varies by provider, but RELURL gives you a specific hostname to point to. Copy it exactly as provided, including the trailing dot if required." },
    { type: "heading", content: "Step 3: Add the Domain to RELURL", level: 2 },
    { type: "paragraph", content: "Once your DNS record is configured, add the domain in your RELURL dashboard. Navigate to the custom domains section, enter your domain name, and click add. RELURL will attempt to verify the domain by checking for the CNAME record." },
    { type: "paragraph", content: "Verification is automatic. If the DNS has propagated, the domain appears as verified within minutes. If verification fails, wait 15 minutes and try again. Some DNS providers cache records longer than others." },
    { type: "heading", content: "Step 4: SSL Certificate Provisioning", level: 2 },
    { type: "paragraph", content: "SSL certificates are critical for short links. Without HTTPS, browsers show security warnings that destroy trust. RELURL automatically provisions SSL certificates for verified custom domains using Let's Encrypt." },
    { type: "paragraph", content: "The provisioning process takes a few minutes after domain verification. Once complete, all short links on your custom domain serve over HTTPS with a valid certificate. No manual certificate management is needed." },
    { type: "paragraph", content: "If you use a CDN or proxy service like Cloudflare in front of your short domain, you may need to configure SSL settings there as well. RELURL supports both flexible and full SSL modes." },
    { type: "heading", content: "Step 5: Start Creating Short Links on Your Domain", level: 2 },
    { type: "paragraph", content: "With the domain verified and SSL active, you can now select it from the domain dropdown when creating short links in RELURL. Every new link you create can use your custom domain as the short domain." },
    { type: "paragraph", content: "Existing short links on the default RELURL domain remain active. You can also migrate important links by creating new versions on your custom domain and updating your sharing channels." },
    { type: "heading", content: "DNS Configuration Cheat Sheet by Provider", level: 2 },
    { type: "list", items: ["Cloudflare: Add CNAME record with proxy status set to DNS only (grey cloud). SSL set to Full or Flexible.", "GoDaddy: Add CNAME record with host as your subdomain and points to the RELURL target hostname.", "Namecheap: Add CNAME record in Advanced DNS. Host field is your subdomain, target is the RELURL hostname.", "Google Domains: Add CNAME record under DNS. Name is your subdomain, data is the target hostname.", "AWS Route 53: Create a CNAME record set. Name is your subdomain, value is the RELURL endpoint."] },
    { type: "heading", content: "Troubleshooting Common Issues", level: 2 },
    { type: "paragraph", content: "The most common issue is DNS propagation delay. If your domain does not verify immediately, wait and retry. Another common problem is using an apex domain without proper support some DNS providers require an ALIAS or ANAME record for root domains." },
    { type: "paragraph", content: "SSL certificate issues are usually resolved by ensuring your DNS points to RELURL before requesting the certificate. If you change DNS after SSL is issued, the certificate needs reissuing. RELURL handles this automatically within 24 hours." },
    { type: "heading", content: "Managing Multiple Custom Domains", level: 2 },
    { type: "paragraph", content: "RELURL supports multiple custom domains on the same account. This is useful for agencies that manage links for multiple brands, or for businesses that want different short domains for different departments or campaigns. Each domain is configured independently and can be selected per link." },
    { type: "faq", faqs: [
      { q: "How long does DNS propagation take for a custom short domain?", a: "Most DNS changes propagate within 5-30 minutes, though some providers may take up to 48 hours. RELURL automatically checks for propagation." },
      { q: "Can I use my existing website domain for short links?", a: "Yes, but use a subdomain like link.yourdomain.com rather than the root domain. This avoids conflicts with your website's DNS records." },
      { q: "Does RELURL provide SSL certificates for custom domains?", a: "Yes. RELURL automatically provisions and renews Let's Encrypt SSL certificates for all verified custom domains at no additional cost." },
      { q: "What happens to my short links if I change DNS providers?", a: "Your short links remain active as long as the DNS records point to RELURL. If you change providers, recreate the CNAME records before the old DNS expires." }
    ] },
    { type: "cta", content: "Set up your custom short domain today with RELURL custom URL shortener and start building brand recognition with every link." }
  ]
}
