export const allPages = [
  { title: "Custom URL Shortener", href: "/custom-url-shortener" },
  { title: "Branded Link Shortener", href: "/branded-link-shortener" },
  { title: "Bulk URL Shortener", href: "/bulk-url-shortener" },
  { title: "Affiliate Link Shortener", href: "/affiliate-link-shortener" },
  { title: "Marketing URL Shortener", href: "/marketing-url-shortener" },
  { title: "Free URL Shortener", href: "/free-url-shortener" },
  { title: "URL Tracking Tool", href: "/url-tracking-tool" },
  { title: "Campaign Link Generator", href: "/campaign-link-generator" },
  { title: "Short URL Analytics", href: "/short-url-analytics" },
  { title: "Custom Alias Generator", href: "/custom-alias-generator" },
  { title: "E-commerce URL Shortener", href: "/ecommerce-url-shortener" },
  { title: "Real Estate Link Shortener", href: "/real-estate-link-shortener" },
  { title: "SaaS Link Shortener", href: "/saas-link-shortener" },
  { title: "Podcast Link Shortener", href: "/podcast-link-shortener" },
  { title: "Event Link Shortener", href: "/event-link-shortener" },
  { title: "News Link Shortener", href: "/news-link-shortener" },
  { title: "Education Link Shortener", href: "/education-link-shortener" },
  { title: "Healthcare Link Shortener", href: "/healthcare-link-shortener" },
  { title: "Nonprofit Link Shortener", href: "/nonprofit-link-shortener" },
  { title: "Travel Link Shortener", href: "/travel-link-shortener" },
  { title: "Restaurant Link Shortener", href: "/restaurant-link-shortener" },
  { title: "Music Link Shortener", href: "/music-link-shortener" },
  { title: "Photography Link Shortener", href: "/photography-link-shortener" },
  { title: "Gaming Link Shortener", href: "/gaming-link-shortener" },
  { title: "Crypto Link Shortener", href: "/crypto-link-shortener" },
  { title: "Agency Link Shortener", href: "/agency-link-shortener" },
  { title: "Startup Link Shortener", href: "/startup-link-shortener" },
  { title: "Ebook Link Shortener", href: "/ebook-link-shortener" },
  { title: "Course Link Shortener", href: "/course-link-shortener" },
  { title: "Webinar Link Shortener", href: "/webinar-link-shortener" },
  { title: "Password Protected Links", href: "/password-protected-links" },
  { title: "Link Expiration", href: "/link-expiration" },
  { title: "URL Shortener API", href: "/url-shortener-api" },
  { title: "Custom Domain Links", href: "/custom-domain-links" },
  { title: "Link in Bio", href: "/link-in-bio" },
  { title: "Shorten PDF Link", href: "/shorten-pdf-link" },
  { title: "Shorten Image URL", href: "/shorten-image-url" },
  { title: "Shorten Video URL", href: "/shorten-video-url" },
  { title: "Shorten GitHub URL", href: "/shorten-github-url" },
  { title: "Shorten Google Drive Link", href: "/shorten-google-drive-link" },
  { title: "Shorten Google Docs Link", href: "/shorten-google-docs-link" },
  { title: "Shorten Dropbox Link", href: "/shorten-dropbox-link" },
  { title: "Shorten YouTube URL", href: "/shorten-youtube-url" },
  { title: "Shorten Instagram URL", href: "/shorten-instagram-url" },
  { title: "Shorten Facebook URL", href: "/shorten-facebook-url" },
  { title: "Shorten WhatsApp Link", href: "/shorten-whatsapp-link" },
  { title: "Shorten LinkedIn URL", href: "/shorten-linkedin-url" },
  { title: "Shorten TikTok URL", href: "/shorten-tiktok-url" },
  { title: "Shorten X URL", href: "/shorten-x-url" },
  { title: "Shorten Discord Invite Link", href: "/shorten-discord-invite-link" },
  { title: "Bitly Alternative", href: "/bitly-alternative" },
  { title: "TinyURL Alternative", href: "/tinyurl-alternative" },
  { title: "Rebrandly Alternative", href: "/rebrandly-alternative" },
  { title: "Short.io Alternative", href: "/short-io-alternative" },
  { title: "Best URL Shortener", href: "/best-url-shortener" },
  { title: "How to Shorten a URL", href: "/how-to-shorten-a-url" },
  { title: "How to Create Short Links", href: "/how-to-create-short-links" },
  { title: "How to Track Link Clicks", href: "/how-to-track-link-clicks" },
  { title: "How to Create QR Codes", href: "/how-to-create-qr-codes" },
  { title: "How to Create Branded Links", href: "/how-to-create-branded-links" },
  { title: "How to Use UTM Parameters", href: "/how-to-use-utm-parameters" },
]

export const socialPages = [
  { title: "Instagram Link Generator", href: "/instagram-link-generator" },
  { title: "WhatsApp Link Generator", href: "/whatsapp-link-generator" },
  { title: "Telegram Link Generator", href: "/telegram-link-generator" },
  { title: "TikTok Bio Link Generator", href: "/tiktok-bio-link-generator" },
  { title: "YouTube Link Generator", href: "/youtube-link-generator" },
  { title: "Facebook URL Generator", href: "/facebook-url-generator" },
  { title: "LinkedIn URL Generator", href: "/linkedin-url-generator" },
  { title: "Pinterest Link Generator", href: "/pinterest-link-generator" },
  { title: "Snapchat Link Generator", href: "/snapchat-link-generator" },
  { title: "Reddit Link Generator", href: "/reddit-link-generator" },
  { title: "Discord Link Generator", href: "/discord-link-generator" },
  { title: "Twitch Link Generator", href: "/twitch-link-generator" },
  { title: "Twitter/X Link Generator", href: "/twitter-link-generator" },
  { title: "Threads Link Generator", href: "/threads-link-generator" },
  { title: "Mastodon Link Generator", href: "/mastodon-link-generator" },
]

export const qrPages = [
  { title: "QR Code Generator", href: "/qr-code-generator" },
  { title: "Dynamic QR Code Generator", href: "/dynamic-qr-code-generator" },
  { title: "Free QR Code Generator", href: "/free-qr-code-generator" },
  { title: "QR Code for WiFi", href: "/qr-code-for-wifi" },
  { title: "QR Code for vCard", href: "/qr-code-for-vcard" },
  { title: "QR Code for Business Card", href: "/qr-code-for-business-card" },
  { title: "QR Code for Restaurant Menu", href: "/qr-code-for-restaurant-menu" },
  { title: "QR Code for App Download", href: "/qr-code-for-app-download" },
  { title: "QR Code for Google Maps", href: "/qr-code-for-google-maps" },
  { title: "QR Code for Google Reviews", href: "/qr-code-for-google-reviews" },
  { title: "QR Code for Facebook", href: "/qr-code-for-facebook" },
  { title: "QR Code for Instagram", href: "/qr-code-for-instagram" },
  { title: "QR Code for LinkedIn", href: "/qr-code-for-linkedin" },
  { title: "QR Code for YouTube", href: "/qr-code-for-youtube" },
  { title: "QR Code for WhatsApp", href: "/qr-code-for-whatsapp" },
  { title: "QR Code for Email", href: "/qr-code-for-email" },
  { title: "QR Code for SMS", href: "/qr-code-for-sms" },
  { title: "QR Code for Phone", href: "/qr-code-for-phone" },
  { title: "QR Code for Event", href: "/qr-code-for-event" },
  { title: "QR Code for PDF", href: "/qr-code-for-pdf" },
  { title: "QR Code for Restaurant", href: "/qr-code-for-restaurant" },
  { title: "QR Code for Hotel", href: "/qr-code-for-hotel" },
  { title: "QR Code for Gym", href: "/qr-code-for-gym" },
  { title: "QR Code for Salon", href: "/qr-code-for-salon" },
  { title: "QR Code for Store", href: "/qr-code-for-store" },
  { title: "QR Code for Resume", href: "/qr-code-for-resume" },
  { title: "QR Code for Portfolio", href: "/qr-code-for-portfolio" },
  { title: "QR Code for Wedding", href: "/qr-code-for-wedding" },
  { title: "QR Code for Birthday", href: "/qr-code-for-birthday" },
  { title: "QR Code for Concert", href: "/qr-code-for-concert" },
  { title: "QR Code for Class", href: "/qr-code-for-class" },
  { title: "QR Code for Fundraiser", href: "/qr-code-for-fundraiser" },
]

export function getRelatedPages(currentHref: string) {
  const all = [...allPages, ...socialPages]
  return all.filter((p) => p.href !== currentHref).slice(0, 6)
}

export const allLandingPages = [...allPages, ...socialPages]
export const allQRCodes = [...allPages, ...socialPages, ...qrPages]
