import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

async function main() {
  console.log("Seeding MarocMarket database...")

  const categories = [
    {
      slug: "immobilier",
      nameFr: "Immobilier",
      nameAr: "عقارات",
      icon: "building",
      color: "#4f46e5",
      order: 1,
      children: [
        { slug: "appartement", nameFr: "Appartement", nameAr: "شقة", order: 1 },
        { slug: "maison", nameFr: "Maison", nameAr: "منزل", order: 2 },
        { slug: "villa", nameFr: "Villa", nameAr: "فيلا", order: 3 },
        { slug: "terrain", nameFr: "Terrain", nameAr: "أرض", order: 4 },
        { slug: "bureau", nameFr: "Bureau", nameAr: "مكتب", order: 5 },
        { slug: "commerce", nameFr: "Commerce", nameAr: "محل تجاري", order: 6 },
      ],
    },
    {
      slug: "automobile",
      nameFr: "Automobile",
      nameAr: "سيارات",
      icon: "car",
      color: "#dc2626",
      order: 2,
      children: [
        { slug: "voitures", nameFr: "Voitures", nameAr: "سيارات", order: 1 },
        { slug: "voitures-occasion", nameFr: "Voitures d'occasion", nameAr: "سيارات مستعملة", order: 2 },
        { slug: "motos", nameFr: "Motos", nameAr: "دراجات نارية", order: 3 },
        { slug: "pieces-auto", nameFr: "Pièces auto", nameAr: "قطع غيار", order: 4 },
      ],
    },
    {
      slug: "high-tech",
      nameFr: "High-Tech",
      nameAr: "إلكترونيات",
      icon: "laptop",
      color: "#2563eb",
      order: 3,
      children: [
        { slug: "smartphones", nameFr: "Smartphones", nameAr: "هواتف ذكية", order: 1 },
        { slug: "ordinateurs", nameFr: "Ordinateurs", nameAr: "أجهزة كمبيوتر", order: 2 },
        { slug: "tablettes", nameFr: "Tablettes", nameAr: "أجهزة لوحية", order: 3 },
        { slug: "consoles", nameFr: "Consoles", nameAr: "أجهزة ألعاب", order: 4 },
      ],
    },
    {
      slug: "mode",
      nameFr: "Mode & Vetements",
      nameAr: "أزياء وملابس",
      icon: "shirt",
      color: "#9333ea",
      order: 4,
      children: [
        { slug: "femme", nameFr: "Femme", nameAr: "نساء", order: 1 },
        { slug: "homme", nameFr: "Homme", nameAr: "رجال", order: 2 },
        { slug: "enfant", nameFr: "Enfant", nameAr: "أطفال", order: 3 },
        { slug: "chaussures", nameFr: "Chaussures", nameAr: "أحذية", order: 4 },
      ],
    },
    {
      slug: "maison",
      nameFr: "Maison & Jardin",
      nameAr: "منزل وحديقة",
      icon: "home",
      color: "#16a34a",
      order: 5,
      children: [
        { slug: "meubles", nameFr: "Meubles", nameAr: "أثاث", order: 1 },
        { slug: "electromenager", nameFr: "Électroménager", nameAr: "أجهزة منزلية", order: 2 },
        { slug: "jardin", nameFr: "Jardin", nameAr: "حديقة", order: 3 },
        { slug: "decoration", nameFr: "Décoration", nameAr: "ديكور", order: 4 },
      ],
    },
    {
      slug: "loisirs",
      nameFr: "Loisirs & Divertissement",
      nameAr: "ترفيه",
      icon: "gamepad-2",
      color: "#f59e0b",
      order: 6,
      children: [
        { slug: "musique", nameFr: "Musique", nameAr: "موسيقى", order: 1 },
        { slug: "livres", nameFr: "Livres", nameAr: "كتب", order: 2 },
        { slug: "collections", nameFr: "Collections", nameAr: "مقتنيات", order: 3 },
      ],
    },
    {
      slug: "sport",
      nameFr: "Sport & Loisirs",
      nameAr: "رياضة",
      icon: "dumbbell",
      color: "#0ea5e9",
      order: 7,
      children: [
        { slug: "fitness", nameFr: "Fitness", nameAr: "لياقة", order: 1 },
        { slug: "velos", nameFr: "Vélos", nameAr: "دراجات", order: 2 },
        { slug: "camping", nameFr: "Camping", nameAr: "تخييم", order: 3 },
      ],
    },
    {
      slug: "beaute",
      nameFr: "Beauté & Santé",
      nameAr: "جمال وصحة",
      icon: "sparkles",
      color: "#ec4899",
      order: 8,
      children: [
        { slug: "cosmetiques", nameFr: "Cosmétiques", nameAr: "مستحضرات تجميل", order: 1 },
        { slug: "parfums", nameFr: "Parfums", nameAr: "عطور", order: 2 },
      ],
    },
    {
      slug: "services",
      nameFr: "Services",
      nameAr: "خدمات",
      icon: "handshake",
      color: "#ca8a04",
      order: 9,
      children: [
        { slug: "plomberie", nameFr: "Plomberie", nameAr: "سباكة", order: 1 },
        { slug: "electricite", nameFr: "Électricité", nameAr: "كهرباء", order: 2 },
        { slug: "nettoyage", nameFr: "Nettoyage", nameAr: "تنظيف", order: 3 },
        { slug: "cours-particuliers", nameFr: "Cours particuliers", nameAr: "دروس خصوصية", order: 4 },
        { slug: "informatique", nameFr: "Informatique", nameAr: "حاسوب", order: 5 },
      ],
    },
    {
      slug: "emploi",
      nameFr: "Emploi & Recrutement",
      nameAr: "وظائف وتوظيف",
      icon: "briefcase",
      color: "#6366f1",
      order: 10,
      children: [
        { slug: "cdi", nameFr: "CDI", nameAr: "عقد دائم", order: 1 },
        { slug: "cdd", nameFr: "CDD", nameAr: "عقد مؤقت", order: 2 },
        { slug: "freelance", nameFr: "Freelance", nameAr: "عمل حر", order: 3 },
        { slug: "stage", nameFr: "Stage", nameAr: "تدريب", order: 4 },
      ],
    },
    {
      slug: "enfants",
      nameFr: "Enfants & Bébés",
      nameAr: "أطفال ورضّع",
      icon: "baby",
      color: "#f472b6",
      order: 11,
      children: [
        { slug: "poussettes", nameFr: "Poussettes", nameAr: "عربات أطفال", order: 1 },
        { slug: "jouets", nameFr: "Jouets", nameAr: "ألعاب", order: 2 },
        { slug: "vetements-enfant", nameFr: "Vêtements", nameAr: "ملابس أطفال", order: 3 },
      ],
    },
    {
      slug: "animaux",
      nameFr: "Animaux",
      nameAr: "حيوانات",
      icon: "paw-print",
      color: "#a3a3a3",
      order: 12,
      children: [
        { slug: "chiens", nameFr: "Chiens", nameAr: "كلاب", order: 1 },
        { slug: "chats", nameFr: "Chats", nameAr: "قطط", order: 2 },
        { slug: "accessoires-animaux", nameFr: "Accessoires", nameAr: "إكسسوارات", order: 3 },
      ],
    },
    {
      slug: "alimentation",
      nameFr: "Alimentation",
      nameAr: "غذاء",
      icon: "apple",
      color: "#ef4444",
      order: 13,
      children: [
        { slug: "fruits-legumes", nameFr: "Fruits & Légumes", nameAr: "فواكه وخضروات", order: 1 },
        { slug: "epicerie", nameFr: "Épicerie", nameAr: "بقالة", order: 2 },
        { slug: "halal", nameFr: "Halal", nameAr: "حلال", order: 3 },
      ],
    },
    {
      slug: "divers",
      nameFr: "Divers",
      nameAr: "متنوعة",
      icon: "grid-3x3",
      color: "#78716c",
      order: 14,
      children: [],
    },
  ]

  for (const cat of categories) {
    const parent = await prisma.marketplaceCategory.upsert({
      where: { slug: cat.slug },
      update: {
        nameFr: cat.nameFr,
        nameAr: cat.nameAr,
        icon: cat.icon,
        color: cat.color,
        order: cat.order,
      },
      create: {
        slug: cat.slug,
        nameFr: cat.nameFr,
        nameAr: cat.nameAr,
        icon: cat.icon,
        color: cat.color,
        order: cat.order,
        isActive: true,
      },
    })

    if (cat.children) {
      for (const child of cat.children) {
        await prisma.marketplaceCategory.upsert({
          where: { slug: `${cat.slug}-${child.slug}` },
          update: {
            nameFr: child.nameFr,
            nameAr: child.nameAr,
            order: child.order,
          },
          create: {
            slug: `${cat.slug}-${child.slug}`,
            nameFr: child.nameFr,
            nameAr: child.nameAr,
            parentId: parent.id,
            order: child.order,
            isActive: true,
          },
        })
      }
    }
  }

  const adminUser = await prisma.marketplaceUser.upsert({
    where: { email: "admin@marocmarket.ma" },
    update: {},
    create: {
      email: "admin@marocmarket.ma",
      name: "Admin MarocMarket",
      role: "ADMIN",
      emailVerified: new Date(),
      isVerified: true,
      verifiedAt: new Date(),
      isActive: true,
    },
  })

  const proUser = await prisma.marketplaceUser.upsert({
    where: { email: "pro@marocmarket.ma" },
    update: {},
    create: {
      email: "pro@marocmarket.ma",
      name: "Pro Immobilier",
      phone: "+212 522-123-456",
      role: "PROFESSIONAL",
      emailVerified: new Date(),
      isVerified: true,
      verifiedAt: new Date(),
      isActive: true,
    },
  })

  const demoUser = await prisma.marketplaceUser.upsert({
    where: { email: "demo@marocmarket.ma" },
    update: {},
    create: {
      email: "demo@marocmarket.ma",
      name: "Mohamed Alaoui",
      phone: "+212 661-234-567",
      role: "USER",
      emailVerified: new Date(),
      isActive: true,
    },
  })

  const demoUser2 = await prisma.marketplaceUser.upsert({
    where: { email: "sara@marocmarket.ma" },
    update: {},
    create: {
      email: "sara@marocmarket.ma",
      name: "Sara Benani",
      phone: "+212 672-345-678",
      role: "USER",
      emailVerified: new Date(),
      isVerified: true,
      verifiedAt: new Date(),
      isActive: true,
    },
  })

  const listings = [
    {
      title: "Appartement moderne 3 chambres - Maarif",
      description: "Appartement de 110m² au 8ème étage avec vue sur la mer. 3 chambres, 2 salles de bain, salon lumineux, cuisine entièrement équipée. Résidence avec gardien et parking. Proche du centre commercial Anfa Place.",
      price: 1450000,
      city: "Casablanca",
      region: "Grand Casablanca",
      slug: "appartement-3-chambres-maarif-casa",
      categorySlug: "immobilier",
      childSlug: "immobilier-appartement",
      isNegotiable: true,
      isProfessional: true,
      viewsCount: 2847,
      favoritesCount: 134,
      condition: "Excellent",
      tags: "lumineux,meublé,parking,mer",
      latitude: 33.5731,
      longitude: -7.5898,
    },
    {
      title: "Villa de luxe avec piscine - Californie",
      description: "Magnifique villa contemporaine de 450m² sur terrain de 1000m². 6 chambres, 4 salles de bain, salon ouvert, cuisine premium, piscine chauffée, jardin paysager, garage 3 voitures. Quartier résidentiel sécurisé avec vue panoramique.",
      price: 5900000,
      city: "Casablanca",
      region: "Grand Casablanca",
      slug: "villa-luxe-piscine-californie",
      categorySlug: "immobilier",
      childSlug: "immobilier-villa",
      isNegotiable: true,
      isProfessional: true,
      isPromoted: true,
      viewsCount: 5621,
      favoritesCount: 289,
      condition: "Neuf",
      tags: "luxe,piscine,contemporain,sécurisé",
      latitude: 33.5500,
      longitude: -7.6167,
    },
    {
      title: "Mercedes-Benz GLC 300 2023 - Full options",
      description: "Mercedes GLC 300 4MATIC de 2023, seulement 15000 km. Couleur Noir Obsidien, intérieur cuir Beige. Panoramique, toit ouvrant, caméra 360°, suspension pneumatique, hayon électrique. Carnet d'entretien complet chez le concessionnaire.",
      price: 585000,
      city: "Rabat",
      region: "Rabat-Salé-Kénitra",
      slug: "mercedes-glc-300-2023-rabat",
      categorySlug: "automobile",
      childSlug: "automobile-voitures",
      isNegotiable: true,
      isProfessional: true,
      viewsCount: 3412,
      favoritesCount: 178,
      condition: "Excellent",
      brand: "Mercedes-Benz",
      model: "GLC 300",
      year: 2023,
      tags: "automatique,4x4,pano,cuir",
      latitude: 34.0209,
      longitude: -6.8416,
    },
    {
      title: "Renault Clio V 2022 - Faible kilométrage",
      description: "Renault Clio V TCe 140 Intens de 2022, 32000 km. Climatisation automatique, écran multimédia 9.3\", caméra de recul, aide au stationnement. Parfait état intérieur et extérieur. Dernier entretien à 30000km.",
      price: 165000,
      city: "Marrakech",
      region: "Marrakech-Safi",
      slug: "renault-clio-v-2022-marrakech",
      categorySlug: "automobile",
      childSlug: "automobile-voitures-occasion",
      isNegotiable: true,
      viewsCount: 1893,
      favoritesCount: 87,
      condition: "Très bon",
      brand: "Renault",
      model: "Clio V",
      year: 2022,
      tags: "essence,automatique,petit kilométrage",
      latitude: 31.6295,
      longitude: -7.9811,
    },
    {
      title: "iPhone 15 Pro Max 256Go - Neuf scellé",
      description: "iPhone 15 Pro Max 256GB couleur Titane Naturel. Neuf sous blister, scellé, garantie Apple 1 an. Acheté officiellement chez iSpot. Prix ferme. Livraison possible en ville.",
      price: 16500,
      city: "Casablanca",
      region: "Grand Casablanca",
      slug: "iphone-15-pro-max-256-neuf",
      categorySlug: "high-tech",
      childSlug: "high-tech-smartphones",
      isNegotiable: false,
      viewsCount: 4567,
      favoritesCount: 312,
      condition: "Neuf",
      tags: "apple,scellé,garantie,livraison",
      latitude: 33.5731,
      longitude: -7.5898,
    },
    {
      title: "MacBook Pro M3 14\" - Comme neuf",
      description: "MacBook Pro M3 14 pouces, 18Go RAM, 512Go SSD. Color Space Gris Sidéral. Acheté en janvier 2024, 3 cycles de charge. Sous AppleCare+ jusqu'en 2027. Avec boîte originale et chargeur.",
      price: 18000,
      city: "Rabat",
      region: "Rabat-Salé-Kénitra",
      slug: "macbook-pro-m3-14-rabat",
      categorySlug: "high-tech",
      childSlug: "high-tech-ordinateurs",
      isNegotiable: false,
      viewsCount: 2134,
      favoritesCount: 156,
      condition: "Comme neuf",
      tags: "apple,garantie,pas cher",
      latitude: 34.0209,
      longitude: -6.8416,
    },
    {
      title: "Robe de mariée broderie main - Taille 38",
      description: "Robe de mariée haute couture, broderie fait main avec perles Swarovski. Taille 38 (modifiable). Jupe princesse avec traine. Voile 3m inclus. Portée une seule fois, pressing professionnel effectué.",
      price: 8500,
      city: "Fès",
      region: "Fès-Meknès",
      slug: "robe-mariee-broderie-main-fes",
      categorySlug: "mode",
      childSlug: "mode-femme",
      isNegotiable: true,
      viewsCount: 987,
      favoritesCount: 45,
      condition: "Très bon",
      tags: "mariage,couture,swarovski",
      latitude: 34.0331,
      longitude: -5.0003,
    },
    {
      title: "Salon cuir 7 places - Tissu premium",
      description: "Salon en cuir véritable 7 places (2+3+2), couleur cognac. Structure en bois massif, rembourrage haute densité. Très bon état, sans defaut. Dimensions totales: 320x180cm. À récupérer sur place.",
      price: 7500,
      city: "Agadir",
      region: "Souss-Massa",
      slug: "salon-cuir-7-places-agadir",
      categorySlug: "maison",
      childSlug: "maison-meubles",
      isNegotiable: true,
      viewsCount: 654,
      favoritesCount: 34,
      condition: "Très bon",
      tags: "cuir,vrai cuir,grand",
      latitude: 30.4278,
      longitude: -9.5981,
    },
    {
      title: "Cours de français - Préparation DELF B2",
      description: "Professeur certifié DELF/DALF propose cours de français pour préparation au DELF B2. Méthode efficace avec taux de réussite 95%. Cours individuels ou en groupe (max 4). Horaires flexibles, 200dh/heure. Localisation: Agdal, Rabat.",
      price: 200,
      city: "Rabat",
      region: "Rabat-Salé-Kénitra",
      slug: "cours-francais-delf-b2-rabat",
      categorySlug: "services",
      childSlug: "services-cours-particuliers",
      isNegotiable: false,
      viewsCount: 1234,
      favoritesCount: 67,
      condition: null,
      tags: "français,delf,examens,agdal",
      latitude: 34.0150,
      longitude: -6.8326,
    },
    {
      title: "PS5 + 4 jeux - Édition Limitée",
      description: "PlayStation 5 Édition Disque + 4 jeux: Spider-Man 2, God of War Ragnarök, FF7 Rebirth, Astro Bot. Manette DualSense Edge incluse. Achetée en décembre 2023, parfait état. Vendue avec la boîte d'origine.",
      price: 4200,
      city: "Tanger",
      region: "Tanger-Tétouan-Al Hoceïma",
      slug: "ps5-4-jeux-tanger",
      categorySlug: "loisirs",
      childSlug: "loisirs-collections",
      isNegotiable: true,
      viewsCount: 2345,
      favoritesCount: 189,
      condition: "Très bon",
      tags: "gaming,playstation,manette",
      latitude: 35.7595,
      longitude: -5.8340,
    },
    {
      title: "Site e-commerce clé en main - Shopify",
      description: "Développeur web expérimenté crée votre site e-commerce professionnel. Inclut: design sur mesure, intégration paiement (Stripe/CMI), gestion stocks, SEO de base, formation. Livraison en 2-3 semaines. Portfolio disponible.",
      price: 8000,
      city: "Casablanca",
      region: "Grand Casablanca",
      slug: "site-ecommerce-cle-en-main",
      categorySlug: "services",
      childSlug: "services-informatique",
      isNegotiable: true,
      isProfessional: true,
      viewsCount: 3456,
      favoritesCount: 234,
      condition: null,
      tags: "web,shopify,e-commerce,design",
      latitude: 33.5731,
      longitude: -7.5898,
    },
    {
      title: "Vélo électrique Decathlon - 45km autonomie",
      description: "Vélo électrique Riverside 500 de Decathlon, 1 an d'utilisation. Batterie lithium 36V, autonomie 45km. 3 niveaux d'assistance, éclairage intégré, porte-bagages. État parfait, entretien récent. Inclut cadenas et casque.",
      price: 5500,
      city: "Meknès",
      region: "Fès-Meknès",
      slug: "velo-electrique-decathlon-meknes",
      categorySlug: "sport",
      childSlug: "sport-velos",
      isNegotiable: true,
      viewsCount: 876,
      favoritesCount: 56,
      condition: "Très bon",
      tags: "électrique,decathlon,autonomie",
      latitude: 33.8935,
      longitude: -5.5547,
    },
    {
      title: "Parfum Tom Ford Oud Wood 100ml - Neuf",
      description: "Parfum Tom Ford Oud Wood, coffret 100ml Eau de Parfum. Neuf, non ouvert. Achat duty-free. Très rare au Maroc. Prix ferme, pas de négociation.",
      price: 3200,
      city: "Casablanca",
      region: "Grand Casablanca",
      slug: "parfum-tom-ford-oud-wood",
      categorySlug: "beaute",
      childSlug: "beaute-parfums",
      isNegotiable: false,
      viewsCount: 5432,
      favoritesCount: 423,
      condition: "Neuf",
      tags: "tom ford,luxe,parfum,oud",
      latitude: 33.5731,
      longitude: -7.5898,
    },
    {
      title: "Berger Allemand - Portée de champion",
      description: "Portée de 6 chiots Berger Allemand pedigree SGHW. Père champion de Belgique, mère championne du Maroc. Première vaccination vermifugés, puce électronique. Disponible à partir de 8 semaines. Photos des parents sur demande.",
      price: 5000,
      city: "Agadir",
      region: "Souss-Massa",
      slug: "berger-allemand-portee-champion",
      categorySlug: "animaux",
      childSlug: "animaux-chiens",
      isNegotiable: true,
      viewsCount: 1876,
      favoritesCount: 234,
      condition: null,
      tags: "chien,berger,pedigree,champion",
      latitude: 30.4278,
      longitude: -9.5981,
    },
    {
      title: "Terrain constructible 500m2 - Route principale",
      description: "Terrain plat de 500m² bordant la route nationale N1. Titre foncier régulier, viabilisé (eau, électricité, gaz). Idéal pour commerce ou habitation. Quartier en plein essor, à 5km du centre-ville.",
      price: 750000,
      city: "Nador",
      region: "Oriental",
      slug: "terrain-500m2-route-nador",
      categorySlug: "immobilier",
      childSlug: "immobilier-terrain",
      isNegotiable: true,
      isProfessional: true,
      viewsCount: 2345,
      favoritesCount: 123,
      condition: null,
      tags: "terrain,constructible,route,viabilisé",
      latitude: 35.1688,
      longitude: -2.9286,
    },
    {
      title: "Offre d'emploi - Développeur React/Next.js",
      description: "Startup marocaine recherche développeur React/Next.js expérimenté (3+ ans). Télétravail possible 3j/semaine. Salaire: 15000-20000dh/mois. Stack: React, Next.js, TypeScript, PostgreSQL, Tailwind. CV et portfolio à envoyer.",
      price: null,
      city: "Casablanca",
      region: "Grand Casablanca",
      slug: "emploi-developpeur-react-nextjs",
      categorySlug: "emploi",
      childSlug: "emploi-cdi",
      isNegotiable: false,
      viewsCount: 6789,
      favoritesCount: 567,
      condition: null,
      tags: "emploi,react,nextjs,télétravail,développeur",
      latitude: 33.5731,
      longitude: -7.5898,
    },
    {
      title: "Poussette Cybex Priam - Like new",
      description: "Poussette Cybex Priam édition.collaboration avec Design Studio. Noir mat, accessoires inclus: rehausseur, sac à langer, adaptateur Maxi-Cosi. Utilisée 6 mois, état impeccable. Pliable d'une main.",
      price: 3800,
      city: "Tanger",
      region: "Tanger-Tétouan-Al Hoceïma",
      slug: "poussette-cybex-priam-tanger",
      categorySlug: "enfants",
      childSlug: "enfants-poussettes",
      isNegotiable: true,
      viewsCount: 567,
      favoritesCount: 78,
      condition: "Très bon",
      tags: "bébé,cybex,poussette,luxe",
      latitude: 35.7595,
      longitude: -5.8340,
    },
  ]

  let createdCount = 0
  for (const listing of listings) {
    const existing = await prisma.marketplaceListing.findUnique({ where: { slug: listing.slug } })
    if (existing) continue

    const category = await prisma.marketplaceCategory.findFirst({
      where: { slug: listing.childSlug || listing.categorySlug },
    })
    if (!category) continue

    const userId = listing.isProfessional ? proUser.id : demoUser.id

    await prisma.marketplaceListing.create({
      data: {
        title: listing.title,
        slug: listing.slug,
        description: listing.description,
        price: listing.price,
        currency: "MAD",
        listingType: listing.categorySlug === "emploi" ? "EMPLOI" : "VENTE",
        status: "ACTIVE",
        condition: listing.condition,
        year: listing.year,
        brand: listing.brand,
        model: listing.model,
        city: listing.city,
        region: listing.region,
        latitude: listing.latitude,
        longitude: listing.longitude,
        isNegotiable: listing.isNegotiable,
        isUrgent: listing.viewsCount > 5000,
        isProfessional: listing.isProfessional || false,
        isPromoted: listing.isPromoted || false,
        promotedUntil: listing.isPromoted ? new Date(Date.now() + 30 * 24 * 60 * 60 * 1000) : null,
        contactPhone: "+212 6XX-XXX-XXX",
        whatsapp: "2126XXXXXXXX",
        tags: listing.tags,
        viewsCount: listing.viewsCount,
        favoritesCount: listing.favoritesCount,
        userId,
        categoryId: category.id,
      },
    })
    createdCount++
  }

  await prisma.marketplaceSubscription.create({
    data: {
      plan: "PRO",
      status: "ACTIVE",
      userId: proUser.id,
      currentPeriodStart: new Date(),
      currentPeriodEnd: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    },
  })

  console.log("Seed completed successfully!")
  console.log(`  - ${categories.length} categories (14 main + subcategories)`)
  console.log(`  - ${createdCount} realistic Moroccan listings`)
  console.log(`  - 4 users: admin, pro, demo, sara`)
  console.log(`  - 1 PRO subscription`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })